version: 2.1
jobs:
  build_and_push_image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t acme-web-app -t tijani119/acme-web-app .

      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u tijani119 --password-stdin

      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push tijani119/acme-web-app:latest

workflows:
  build_and_push_image:
    jobs:
      - build_and_push_image
